<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\InstallBundle\Command\InstallCommand' shared autowired service.

$a = ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'};

return $this->services['Pimcore\Bundle\InstallBundle\Command\InstallCommand'] = new \Pimcore\Bundle\InstallBundle\Command\InstallCommand(new \Pimcore\Bundle\InstallBundle\Installer(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLoggerService.php')) && false ?: '_'}, $a), $a);
