<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUc8x8x4\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUc8x8x4/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUc8x8x4.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUc8x8x4\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerUc8x8x4\installerProdDebugProjectContainer([
    'container.build_hash' => 'Uc8x8x4',
    'container.build_id' => '6863f0d8',
    'container.build_time' => 1553156776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUc8x8x4');
